### ISSUE TITLE
Status?

### ISSUE THREAD

**Issue by valnub** [impressivewebs/frontend-feeds#18]
Is this list still up to date?

**Comment by mszynka** [comment]
90% of them are still accessible. The project itself is not maintained though.

**Comment by MartinMuzatko** [comment]
http://rss.badassjs.com/ is outdated (last post 2014) and the rss feed is not available anymore

**Comment by valnub** [comment]
@MartinMuzatko Why don't you create a PR? :-)

**Comment by MartinMuzatko** [comment]
To see the interest getting started here again before investing time into a dead project ;)
but lets revive this.
https://github.com/impressivewebs/frontend-feeds/pull/19

**Comment by impressivewebs** [comment]
I've revisited this feeds list and it's now up to date as of March 2020.
