### ISSUE TITLE
Suggestion: sidebar.io

### ISSUE THREAD

**Issue by KMB** [impressivewebs/frontend-feeds#22]
Category: Developer & Designer News
URL: https://sidebar.io/
Description: 
They describe themself as "The five best design links, every day." and "Since 2012, Sidebar has been collecting the best links about UI design, typography, CSS, user research, and all other facets of design."

There is a whole community that suggests links, votes, etc, but to be honest I just subscribe to the RSS feed, which gives me 5 links a day. It scratches my FOMO-itch without spamming my RSS reader.

**Comment by impressivewebs** [comment]
Thanks for the suggestion. Sidebar is actually mainly a newsletter. I used to include newsletter feeds in this repo, but I've removed those now, so I won't include Sidebar.
