### ISSUE TITLE
CSS Weekly

### ISSUE THREAD

**Issue by ZoranJambor** [impressivewebs/frontend-feeds#23]
My newsletter [CSS Weekly](https://css-weekly.com) is also available via [RSS](https://feeds.feedburner.com/CSS-Weekly).  

Do you think it could qualify for _Developer & Designer News_ section?

**Comment by linxz** [comment]
CSS weekly is awesome

**Comment by ZoranJambor** [comment]
Thank you so much, @linxz! <3

**Comment by impressivewebs** [comment]
Sorry for the late reply on this @ZoranJambor. I used to include newsletter RSS feeds in this list, but I removed them all for the 2020 update. I feel that RSS isn't the primary way that newsletters are accessed, and there's quite a few to include, so maybe better not to include them. Maybe if enough people say something then I can add them again but for now I won't include any RSS feeds for newsletters. Thanks!
