### ISSUE TITLE
Suggestion: writingjavascript.com

### ISSUE THREAD

**Issue by tirithen** [impressivewebs/frontend-feeds#27]
Hi, I'm the author of the JavaScript blog Writing JavaScript and I would like to suggest the blog for this list. The blog focuses much of its articles around plain JavaScript rather than the large frameworks.

If you are interested the info is:

Author: Fredrik Söderström
URL: https://writingjavascript.com
RSS: https://writingjavascript.com/rss.xml

**Comment by impressivewebs** [comment]
Thanks, looks decent. I notice you have only published one article in the past ~5 months. I'll keep this issue open for a little while and I'll take a look at the site again later. If I see that you're publishing somewhat regularly, I'll add it. I just don't want the list to be too big and have too many sites that only publish like once a year or something. Thanks.

**Comment by tirithen** [comment]
@impressivewebs Thanks for considering the blog, yes there has been a gap for last 5 months. I'll be writing more in the coming months.

I like that you curate the list to keep up the quality. Lets see in a few months then :)

**Comment by impressivewebs** [comment]
@tirithen Thanks, I just added your blog. :)
