### ISSUE TITLE
Add "Frontend Masters Blog"

### ISSUE THREAD

**Issue by imlutr** [impressivewebs/frontend-feeds#35]
https://frontendmasters.com/blog/

It seems to be the new cool blog in town. It's a multi-author blog. That's where people like Chris Coyier write (= creator of CSS-Tricks - which should no longer be on this list too in my opinion, as there hasn't been a post in years).

**Comment by impressivewebs** [comment]
Added. thanks! I'll leave CSS-Tricks up for now as things have picked up there a little bit.
