### ISSUE TITLE
Change dailydevlinks to Unicorn Club

### ISSUE THREAD

**Issue by AdamMarsden** [impressivewebs/frontend-feeds#39]
Thanks for the shoutout @impressivewebs we've since re-branded dailydevlinks to Unicorn Club

Here are the updated links for you!

[RSS](https://unicornclub.dev/feed/) [Unicorn Club](https://unicornclub.dev/)

**Comment by impressivewebs** [comment]
Thanks @AdamMarsden, just updated it.
